# -*- coding: utf-8 -*-
"""Tripadvisor Hotel Review

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zg5zJHeZYiVxbuMRPvJxYfVnhKWf83WL
"""

nama = "Saadillah Noer"
nik = 3275091002980011

print("nama =",nama, "\n", "nik =", nik)

"""# Bagian Baru

**Menggunakan Model untuk Melakukan Prediksi**
"""

import tensorflow as tf
import numpy as np
from tensorflow import keras
xs = np.array([1.0,  2.0, 3.0, 4.0, 5.0, 6.0], dtype=float)
ys = np.array([4.0, 6.0, 8.0, 10.0, 12.0, 14.0], dtype=float)

model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])

model.compile(optimizer='sgd', loss='mean_squared_error')

model.fit(xs, ys, epochs=150)

"""**Model Sequential dengan Beberapa Layer**"""

model = tf.keras.Sequential([
                             keras.layers.Dense(units=1, input_shape=[1]),
                             keras.layers.Dense(units=8),
                             keras.layers.Dense(units=1)
])

"""**Membuat Model untuk Klasifikasi Dua Kelas**"""

import pandas as pd
df = pd.read_csv('tripadvisor_hotel_reviews.csv')

df.info()

df.head()

dataset = df.values

# pilih 5 kolom terakhir sebagai atribut
X = dataset[:,1:6]
# bilangan sebelum koma untuk memilih baris pada dataframe
# bilangan setelah koma untuk memilih kolom pada dataframe

y = dataset[:,0]

# Normalization
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)
X_scale

# pisahkan data training dan testing
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_scale, y, test_size=0.3)

from keras.models import Sequential
from keras.layers import Dense

model = Sequential([
                    Dense(32, activation='relu', input_shape=(5,)),
                    Dense(32, activation='relu'),
                    Dense(1, activation='sigmoid'),])

model.compile(optimizer='sgd',
              loss='binary_crossentropy',
              metrics=['accuracy'])

"""**Membuat dan Melatih Model dengan Banyak Kelas**"""

import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense

df = pd.read_csv('tripadvisor_hotel_reviews.csv')
df

df = df.drop(columns='Review')

X_train, X_test, Y_train, Y_test = train_test_split(X_scale, y, test_size=0.3)

model = Sequential([    
                   Dense(64, activation='relu', input_shape=(4,)),    
	                 Dense(64, activation='relu'),    
	                 Dense(3, activation='softmax'),])

model.compile(optimizer='Adam',
	              loss='categorical_crossentropy',
	              metrics=['accuracy'])